version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - (Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin 639080980474.dkr.ecr.eu-west-2.amazonaws.com
  build:
    commands:
      - echo Building Docker image....
     
      
  post_build:
    commands:
      # Additional commands for post-build steps (e.g., tests, artifacts, etc.)
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
