version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 639080980474.dkr.ecr.eu-west-2.amazonaws.com
  build:
    commands:
      - echo Building Docker image....
      - docker build -t apidocker .
      - echo Building Docker image completed....
      - docker tag apidocker:dev 639080980474.dkr.ecr.eu-west-2.amazonaws.com/apidocker:dev 
      - echo taging of Docker image completed....
  post_build:
    commands:
      # Additional commands for post-build steps (e.g., tests, artifacts, etc.)
      - echo Build completed successfully.
      - docker push 639080980474.dkr.ecr.eu-west-2.amazonaws.com/apidocker:dev
      - echo docker push completed successfully.

artifacts:
  files:
    - '**/*'
