version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region eu-west-2 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo Building Docker image...
      - docker build -t awscodepipelinedemo .
      - echo Pushing Docker image to ECR...
      - docker tag apidocker:latest 639080980474.dkr.ecr.eu-west-2.amazonaws.com/apidocker:latest
      - docker push 639080980474.dkr.ecr.eu-west-2.amazonaws.com/apidocker:latest
  post_build:
    commands:
      # Additional commands for post-build steps (e.g., tests, artifacts, etc.)
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
